### ISSUE TITLE
2.0_dashboard--new-user

### ISSUE THREAD

**Issue by jrdnndtsch** [luclemo/linkinbio-ui#1]
Does this view only show up if the user has no created posts?

**Comment by luclemo** [comment]
@jrdnndtsch Yes, exactly. There are three possible flows that lead to this screen:

- New user signs up. Ends up here on submit of sign-up form.
- New user has created an account, but not created posts yet. End up here on submit of login form.
- Existing user has deleted all their existing posts. End up here on confirmation that they want to delete all their posts.

In other words, it is the default dashboard for any logged-in user who has no posts.
