### ISSUE TITLE
Do we need to rethink the "view blog" button in the header

### ISSUE THREAD

**Issue by luclemo** [luclemo/linkinbio-ui#10]
@deartrudence @jrdnndtsch 

So I created a logged-in user view of the blog (531fd45), but now I'm rethinking it.

Mostly because if I'm logged-in and I see that grid two things happen which could be super confusing:

1. Aren't I expecting to see what my public sees? That page will look very different to non-logged-in users no (no header bar etc)?
2. I'm now probably expecting to be able to edit any one of those posts by clicking on one of the images? Not that this isn't _impossible_ functionality to add, but do we want to add more unnecessary dev work?

**Suggest solution:**
We scrap the "logged-in" blog view. The `View blog` button will always open the blog (as seen by the public, ie no logged-in state, ) in a new tab.

Let me know what you think here or if I'm missing something important.

**Comment by deartrudence** [comment]
this sounds good to me and probably makes the most sense.

**Comment by luclemo** [comment]
Ok great, just sit on the grid view (`6.0_blog--logged-in`) until I make it a non-logged-in view.
The styles for the images stand though :)
