### ISSUE TITLE
clicking show on a single post from the dashboard

### ISSUE THREAD

**Issue by jrdnndtsch** [luclemo/linkinbio-ui#12]
when you click the show icon what happens

1. when it is just a link does it just take you to the external site

2. When it is a blog post does it take you to the blog post? Should it be in a new tab? Should there be some quick way to get back to the dashboard?

**Comment by luclemo** [comment]
Ok so in my mind:

1. If post is link && published 👉 open link in new tab
2. If post is post && published 👉 open post in new tab
3. If post is link || post && draft 👉 open edit view (not new tab)

In two first cases the quick way back is to close the tab lol.
In third case there's a quick way back to dashboard.

Make sense?

**Comment by luclemo** [comment]
@jrdnndtsch 

Wait wait wait! I'm wrong about case 3.

If it's a post && in draft mode, ckicking show will open a _preview_ of the post, not edit view. I suggest a thin band message at the top indicating they are looking at a preview with a link to edit or go back to dashboard. Message styles coming today.

As for the link in draft mode... I mean it's a link right? So the _preview_ of that could just be... the link open in a new tab anyway...?

**Comment by luclemo** [comment]
This is sorted 💪
