### ISSUE TITLE
What is the flow to edit from dashboard

### ISSUE THREAD

**Issue by jrdnndtsch** [luclemo/linkinbio-ui#4]
In the dashboard view when the user clicks 'edit' on a single instagram

does it either
1. Take them to 4.0 choose action (this stuff is likely not edited too often after initial selection so feels like an extra step).
2. Take them to the edit blog post / edit link page (ex. one sent on slack). In this case what if I want an instagram to change from a post to a link or vice versa.

<img width="935" alt="screen shot 2018-01-23 at 5 47 58 pm" src="https://user-images.githubusercontent.com/10091647/35288651-9effff58-0065-11e8-854f-514a1a5af28c.png">

**Comment by luclemo** [comment]
It takes them to the blog post / edit link page (ie #2).
My plan is to add a "make this a link / change to link" action to that view (and vice versa if it's a link already)
