### ISSUE TITLE
if the user 'deletes' a post is it added back to the instagram photo options for selection?

### ISSUE THREAD

**Issue by jrdnndtsch** [luclemo/linkinbio-ui#5]
if it is just flat out deleted from linkinbio - should we have some good messaging that deleting this will remove it from the app and you can't re-add it

if we decide to not delete it flat out and add it back to the options to future posts do we want to do anything to handle the fact that, that photo may be deleted from their instagram (maybe this is too granular)

**Comment by luclemo** [comment]
I think expected behaviour would be:
Post/link is deleted.
Image is back in the selection grid.

Hope I understood this?
