### ISSUE TITLE
icon export

### ISSUE THREAD

**Issue by jrdnndtsch** [luclemo/linkinbio-ui#6]
for some reason when I export them the colors un-mix and the icons look wonky :|

**Comment by luclemo** [comment]
Yes I am going to export all icons as SVGs...
Looking into exporting as an svg sprite which will be even better.

**Comment by luclemo** [comment]
Closing this as svg sprite has been added in last commit. See notes [on that commit](https://github.com/luclemo/linkinbio-ui/commit/743ce7fb375fc8014257a9713023012a3b8a7668) for details on how to use it :)
