### ISSUE TITLE
CTA for create new post in menu

### ISSUE THREAD

**Issue by jrdnndtsch** [luclemo/linkinbio-ui#7]
just wondering if maybe this would be useful? I feel like maybe the more likely action will be to create a post v. viewblog.

Right now the only way to get to create a post is from the dashboard.

I feel like there is a good use case where you finish making one post, preview and then want to make another

**Comment by luclemo** [comment]
Good point! Let me fix that.

**Comment by luclemo** [comment]
Ok based on our chat this morning we're going to leave things as they are for the "create post" button.

To recap: the default view when logged in is the dashboard view which has the big "create new post" button so they are pretty much always having that option _unless_ they are

1. in selecting/creating/editing mode, in which case they are in process of creating a post.
2. in their account settings, in which case they are busy doing other stuff and a natural flow would be to go back to dashboard.
