### ISSUE TITLE
Link to the dashboard

### ISSUE THREAD

**Issue by jrdnndtsch** [luclemo/linkinbio-ui#8]
right now there is no explicit link to the dashboard on the menu. 

Can be accessed once you're in create_post with the back to dashboard link, and right now is set up as the home so you can get to it by clicking link in bio in nav, but maybe this should change and there should be a dashboard link?

**Comment by luclemo** [comment]
Hmmm, ok. [This question is also related](https://github.com/luclemo/linkinbio-ui/issues/7). I think I should rethink the actual header/menu now that flow is better fleshed out.

**Comment by luclemo** [comment]
Based on our chat, I will revamp the header and include an explicit path back to dashboard at all times.

**Comment by luclemo** [comment]
Solved with 9ff923148af1c4ea19cc8f1cbc340e848e1c0502
