### ISSUE TITLE
5.0 create_post - what triggers the update on the campaign name

### ISSUE THREAD

**Issue by jrdnndtsch** [luclemo/linkinbio-ui#9]
what is the interaction for editing the campaign name? does it resave on each change of the input? is there some kind of trigger?

<img width="284" alt="screen shot 2018-01-26 at 12 37 46 pm" src="https://user-images.githubusercontent.com/10091647/35438207-e58daba0-0295-11e8-80b6-efad55d3afe4.png">

**Comment by luclemo** [comment]
I was thinking inline edit, a la google docs (like when you want to rename the doc). Just have to provide an in-edit-mode state. Coming today.

**Comment by jrdnndtsch** [comment]
cool - it looks like google docs does it on 'blur' when you click out of the input. I think that works well

**Comment by luclemo** [comment]
Yeah I mean in my mind when the user clicks on the pencil icon or anywhere on the words, the words block turns into a focus field and icon switches to check mark. When they are done editing, either clicking on check mark or hitting enter would commit the changes and field exists focus mode. 

Cancelling an edit could be escape key I guess. If we also need a cancel icon then we can add an X icon right next to the check-mark icon.

Thoughts?

**Comment by luclemo** [comment]
Oh never mind, I just saw what you did. Perfect. Let's just add the pencil icon (as an indicator that it's possible to edit that field). It can be hidden on focus and no need for any other icons 👌
